# Generated by Django 2.2.3 on 2019-07-31 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter your first name.', max_length=120)),
                ('family_name', models.CharField(help_text='Please enter your family name.', max_length=120)),
                ('date_of_birth', models.DateField(help_text='Please enter your date of birth. (i.e. YYYY-MM-DD)')),
                ('email_address', models.EmailField(help_text='Please enter a valid email address.', max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='VisionBoard',
            new_name='GoalBoard',
        ),
        migrations.DeleteModel(
            name='ProgressTracker',
        ),
        migrations.RenameField(
            model_name='goalboard',
            old_name='goals',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Person'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(default=1, help_text='Select a category for this resource', on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(to='core.Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='pairs',
            field=models.ManyToManyField(through='core.Pair', to='core.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pair',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor', to='core.Person'),
        ),
        migrations.AddField(
            model_name='pair',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentee', to='core.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Person')),
                ('email', models.EmailField(help_text='Please enter a valid email address.', max_length=254)),
                ('first_name', models.CharField(help_text='Please enter your first name.', max_length=120)),
                ('family_name', models.CharField(help_text='Please enter your family name.', max_length=120)),
                ('reference_name', models.CharField(help_text='Please enter a professional reference.', max_length=30)),
                ('reference_Phone', phonenumber_field.modelfields.PhoneNumberField(help_text="Please enter your professional reference's phone number.", max_length=128, region=None)),
                ('reference_name2', models.CharField(help_text='Please enter a personal reference name.', max_length=30)),
                ('reference_phone2', phonenumber_field.modelfields.PhoneNumberField(help_text="Please enter your personal reference's phone number.", max_length=128, region=None)),
                ('date_of_birth', models.DateField(help_text='Please enter your date of birth. (i.e. YYYY-MM-DD)')),
                ('why', models.TextField(help_text='Please briefly describe why you want to become a foster mentor.', max_length=200)),
                ('availabilty', models.TextField(help_text='Please list the days and times you would be available to mentor.', max_length=200)),
                ('address', models.CharField(help_text='Please enter your full address', max_length=80)),
                ('education', models.CharField(choices=[('High School / GED', 'High School / GED'), ('Some College', 'Some College'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Masters' Degree", "Master's Degree"), ('PhD', 'PhD'), ('None', 'None')], default='None', max_length=30)),
                ('category', models.ManyToManyField(help_text='Please select a skill speciality.', to='core.Category')),
            ],
        ),
    ]
