# Generated by Django 2.2.3 on 2019-08-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pairs',
        ),
    ]
