# Generated by Django 2.2.4 on 2019-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190806_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='upload',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
