# Generated by Django 2.2.4 on 2019-08-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_person_pairs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='availabilty',
            new_name='availability',
        ),
    ]
