# Generated by Django 2.2.4 on 2019-08-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190803_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='pair',
        ),
    ]
