# Generated by Django 2.2.4 on 2019-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.FileField(default='images/otterprofile.jpg', upload_to=''),
        ),
    ]
