# Generated by Django 2.2.4 on 2019-08-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190803_2346'),
        ('core', '0003_remove_goal_pair'),
    ]

    operations = [
    ]
