# Generated by Django 2.2.4 on 2019-08-03 16:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190802_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Please enter your full address', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.TextField(blank=True, help_text='Please list the days and times you would be available to mentor.', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Please enter a valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, help_text='Please enter your family name.', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Please enter your first name.', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Please enter a professional reference.', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='reference_name2',
            field=models.CharField(blank=True, help_text='Please enter a personal reference name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='reference_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter your professional reference's phone number.", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='reference_phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Please enter your personal reference's phone number.", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='why',
            field=models.TextField(blank=True, help_text='Please briefly describe why you want to become a foster mentor.', max_length=200),
        ),
    ]
