# Generated by Django 2.2.4 on 2019-08-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190803_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='how_to_achieve',
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default='', help_text='Please a list of things you need to do to accomplish your goal.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(help_text='Please enter your goal here.', max_length=120),
        ),
    ]
