# Generated by Django 2.2.3 on 2019-08-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
