# Generated by Django 2.2.4 on 2019-08-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190803_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='name',
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
