# Generated by Django 2.2.4 on 2019-08-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190811_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.FileField(default='core/static/images/default_avatar.png', upload_to=''),
        ),
    ]
