# Generated by Django 2.2.4 on 2019-08-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190811_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.FileField(default='https://www.nicepng.com/png/full/73-730154_open-default-profile-picture-png.png', upload_to='profile_pictures'),
        ),
    ]
