# Generated by Django 2.2.4 on 2019-08-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190811_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.FileField(default='https://projectimpact.s3.amazonaws.com/media/service_default_avatar_182956.png', upload_to=''),
        ),
    ]
