# Generated by Django 2.2.4 on 2019-08-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190811_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
