# Generated by Django 2.2.4 on 2019-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190811_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(default='chatroom', max_length=100),
        ),
    ]
